name: Robot Framework - E2E Tests

on:
  push:
      branches: [ master, main, develop ]
  pull_request:
      branches: [ master, main, develop ]
      
jobs:
  robot_tests:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Robot Framework Tests 
        uses: joonvena/robotframework-docker-action@v1.0
        with:    
          robot_threads: 2
