name: e2e-Tests-RobotFramework

on:
  push:
      branches: [ master, main, develop ]
  pull_request:
      branches: [ master, main, develop ]
      
jobs:
  robot-framwwork-run:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:    
          robot_threads: 2           
          robot_options: 'robot -d ./logs'
          robot_tests_dir: 'tests'
          robot_reports_dir: 'reports'
