name: Robot Framework - E2E Tests

on:
  pull_request:
      branches: [ master, develop ]
      
jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install Robot Framework
        run: |
          pip install robotframework
        
      - name: Install library Browser(Playwright)        
        run: |
          pip install -U pip
          pip install robotframework-browser
          pip install -U robotframework-browser

      - name: Install Node Dependencies        
        run: |
          rfbrowser init 

      - name: E2E Tests ✅        
        run: |
          robot -d ./logs -v BROWSER:chromium -v HEADLESS:true tests/   
    
      - name: Upload Reports 🚀
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Execution Test Reports
          path: logs/
          if-no-files-found: warn
        
      - name: Slack Notification - Success        
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: pipeline-notifications
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png
          SLACK_TITLE: 'All tests passed successfully'          
          SLACK_MESSAGE: ':robot:  Tests after Pull Request passed  :robot:'
          SLACK_USERNAME: SUCCESS
      
      - name: Slack Notification - Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: pipeline-notifications
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.novaconcursos.com.br/portal/wp-content/uploads/2013/12/erro-que-concurseiro-comente-300x3001.png          
          SLACK_TITLE: 'Some tests failed'
          SLACK_MESSAGE: ':fire:  Tests after Pull Request failed  :fire:'
          SLACK_USERNAME: FAILURE