name: Robot Framework - E2E Tests

on:
  push:
      branches: [ master, main, develop ]
  pull_request:
      branches: [ master, main, develop ]
      
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Robot Framework Tests
        uses: joonvena/robotframework-docker-action@v1.1
        with:    
          robot_threads: 4
          robot_tests_dir: 'tests'
          robot_reports_dir: 'reports'
