name: Robot Framework - E2E Tests

on:
  push:
      branches: [ master, main, develop ]
  pull_request:
      branches: [ master, main, develop ]
      
jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Robot Framework
        run: |
          pip install robotframework          
      - name: Install Robot Framework - Browser
        run: |
          pip install -U pip
          pip install robotframework-browser
          pip install -U robotframework-browser          
      - name: Install Node Dependencies
        run: |
          rfbrowser init
      - name: Run Robot Framework Tests
        run: robot -d ./logs tests/         
