name: Robot Framework - E2E Tests

on:
  pull_request:
      branches: [ master, develop ]
      
jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Install Robot Framework
        run: |
          pip install robotframework          
      - name: Install library - Browser(Playwright)
        run: |
          pip install -U pip
          pip install robotframework-browser
          pip install -U robotframework-browser          
      - name: Install Node Dependencies
        run: |
          rfbrowser init

      - name: E2E Tests ✅        
        run: |
          robot -d ./logs -v BROWSER:chromium -v HEADLESS:true tests/
        continue-on-error: true   
    
      - name: Upload Reports 🚀
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Execution Test Reports
          path: logs/*.html
          if-no-files-found: warn

      - name: Slack Notification - Success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: pipeline-notifications
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png
          SLACK_MESSAGE: 'Testes do PR executados com sucesso!  :robot:'
          SLACK_TITLE: 'Testes do PR executados com sucesso!  :white_check_mark:'          
          SLACK_USERNAME: SUCCESS
      
      - name: Slack Notification - Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}
          SLACK_CHANNEL: pipeline-notifications
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.novaconcursos.com.br/portal/wp-content/uploads/2013/12/erro-que-concurseiro-comente-300x3001.png          
          SLACK_MESSAGE: 'Falha na execução dos testes do PR!  :fire:'
          SLACK_TITLE: 'Falha na execução dos testes do PR!  :fire:'
          SLACK_USERNAME: FAILURE